### ISSUE TITLE
Exception in Tkinter callback Traceback (most recent call last):   File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1883, in __call__     return self.func(*args)   File "C:\Users\user\Desktop\main.py", line 555, in <lambda>     command=lambda: user_auth(e1.get(), e2.get()))   File "C:\Users\user\Desktop\main.py", line 526, in user_auth     ud(username)   File "C:\Users\user\Desktop\main.py", line 482, in ud     t2 = bill(tab_main, username)   File "C:\Users\user\Desktop\main.py", line 403, in bill     clicked.set(options[0]) IndexError: list index out of range PLSE HELP

### ISSUE THREAD

**Issue by KES2619** [anpct/billingsystem#3]

**Comment by anpct** [comment]
Similar issue as before, fixed it and updated _main.py_

**Comment by KES2619** [comment]
thankyou for the help. without ur help i wouldn't have been able to
complete this project.
